### ISSUE TITLE
Error with nested projects (mono repos)

### ISSUE THREAD

**Issue by dfalling** [macklinu/danger-plugin-no-test-shortcuts#18]
I have my Circle CI set to run certain tests in a subdirectory via setting the `working_directory` property.  This trips up the plugin, as it seems to have the absolute path for the files, but is running from the working directory:
```
ENOENT: no such file or directory, open 'mobile/tests/App.js'
Error: ENOENT: no such file or directory, open 'mobile/tests/App.js'
```

Has anyone found a workaround for this?

Thanks!

**Comment by macklinu** [comment]
Thanks for the report. I haven't worked with monorepos, so this isn't a test case I've thought about.

Right now, this plugin just takes the file paths returned from `danger.git` and passes that into `fs.readFileSync()`.

https://github.com/macklinu/danger-plugin-no-test-shortcuts/blob/ebd8c91e333d96a7c6d6e5e6fa1411d0fb460a40/src/index.ts#L44-L49

Perhaps we should be more careful when resolving the file path as a solution to this issue? Do you have a link to the Circle CI build or GitHub repo where you're experiencing this issue (if your project is open source)?

**Comment by dfalling** [comment]
I don't have a link- it's closed source.  I'll make a small example in a public repo to demonstrate it.

**Comment by dfalling** [comment]
Sorry for the delay, here's a PR for a public repo exhibiting the problem:
https://github.com/dfalling/danger-test/pull/1
